---
pipeline:
  build-docker:
    when:
      branch: [development, stage, master]
      event: [pull_request, push, tag]
    image: docker-utilities.binrepo.cglcloud.in/drone-plugin-cgl-docker:3-stable
    repo: connecteddataapi
    env: stage
    tags: "${DRONE_COMMIT_SHA:0:7}"
    captain_file: .captain.yml
    dockerfile: Dockerfile
    skip_existing: true
    xray_full_results: true
  add-secrets-for-captain-dev:
    when:
      event: [push, tag]
      branch: [development]
    image: docker-utilities.binrepo.cglcloud.in/drone-plugin-cgl-secrets:1-stable
    team: anhdomainapi
    app: connecteddataapi
    k8s_env: dev
    captain_config: true
    secrets:
      - dev_node_env
    key_value_pairs:
      NODE_ENV: dev_node_env
    run_apply: true
  plan-on-push-dev:
    when:
      branch: [development]
      event: [push, tag]
    image: docker-utilities.binrepo.cglcloud.in/captain:1.13.3-rc1
    env: dev
    version: "${DRONE_COMMIT_SHA:0:7}"
    run_apply: false
    captain_file: .captain.yml
    dockerfile: Dockerfile
  deploy-on-push-dev:
    when:
      branch: [development]
      event: [push, tag]
    image: docker-utilities.binrepo.cglcloud.in/captain:1.13.3-rc1
    env: dev
    version: "${DRONE_COMMIT_SHA:0:7}"
    run_apply: true
    captain_file: .captain.yml
    dockerfile: Dockerfile
  add-secrets-for-captain-stage:
    when:
      branch: [stage]
      event: [push, tag]
    image: docker-utilities.binrepo.cglcloud.in/drone-plugin-cgl-secrets:1-stable
    team: anhdomainapi
    app: connecteddataapi
    k8s_env: stage
    captain_config: true
    secrets:
      - stage_node_env
    key_value_pairs:
      NODE_ENV: stage_node_env
    run_apply: true
  plan-on-push-stage:
    when:
      branch: [stage]
      event: [push, tag]
    image: docker-utilities.binrepo.cglcloud.in/captain:1.13.3-rc1
    env: stage
    version: "${DRONE_COMMIT_SHA:0:7}"
    run_apply: false
    captain_file: .captain.yml
    dockerfile: Dockerfile
  deploy-on-push-stage:
    when:
      branch: [stage]
      event: [push, tag]
    image: docker-utilities.binrepo.cglcloud.in/captain:1.13.3-rc1
    env: stage
    version: "${DRONE_COMMIT_SHA:0:7}"
    run_apply: true
    captain_file: .captain.yml
    dockerfile: Dockerfile
  add-secrets-for-captain-prod:
    when:
      branch: [master]
      event: [push, tag]
    image: docker-utilities.binrepo.cglcloud.in/drone-plugin-cgl-secrets:1-stable
    team: anhdomainapi
    app: connecteddataapi
    k8s_env: prod
    captain_config: true
    secrets:
      - prod_node_env
    key_value_pairs:
      NODE_ENV: prod_node_env
    run_apply: true
  plan-on-push-prod:
    when:
      branch: [master]
      event: [push, tag]
    image: docker-utilities.binrepo.cglcloud.in/captain:1.13.3-rc1
    env: prod
    version: "${DRONE_COMMIT_SHA:0:7}"
    run_apply: false
    captain_file: .captain.yml
    dockerfile: Dockerfile
  deploy-on-push-prod:
    when:
      branch: [master]
      event: [push, tag]
    image: docker-utilities.binrepo.cglcloud.in/captain:1.13.3-rc1
    env: prod
    version: "${DRONE_COMMIT_SHA:0:7}"
    run_apply: true
    captain_file: .captain.yml
    dockerfile: Dockerfile
